databases:
  - name: futmx_database
    databaseName: futmx_database
    user: futmx_lodge

services:
  - type: web
    name: futmx_lodge
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn futmx_lodge.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: futmx_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4