# Generated by Django 4.2 on 2023-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='level',
            field=models.CharField(blank=True, choices=[('1L', '100 Level'), ('2L', '200 Level'), ('3L', '300 Level'), ('4L', '400 Level'), ('5L', '500 Level')], max_length=2),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='religion',
            field=models.CharField(blank=True, choices=[('IS', 'Muslim'), ('CR', 'Christian'), ('OT', 'Other')], max_length=2),
        ),
    ]
