# Generated by Django 4.2 on 2023-12-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_department_useraccount_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='department',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='level',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='religion',
        ),
    ]
