# Generated by Django 4.2 on 2023-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agent_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='telagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
