# Generated by Django 4.2 on 2023-12-05 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_mates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roommate',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roommate',
            name='level',
            field=models.CharField(blank=True, choices=[('1L', '100 Level'), ('2L', '200 Level'), ('3L', '300 Level'), ('4L', '400 Level'), ('5L', '500 Level')], max_length=2),
        ),
        migrations.AddField(
            model_name='roommate',
            name='religion',
            field=models.CharField(blank=True, choices=[('IS', 'Muslim'), ('CR', 'Christian'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AddField(
            model_name='roommate',
            name='searching',
            field=models.BooleanField(default=True),
        ),
    ]
