# Generated by Django 4.2 on 2023-11-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('GK', 'Gk'), ('BS', 'Bosso')], max_length=2)),
                ('area', models.CharField(max_length=50)),
                ('available_rooms', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(default='11756.jpg', upload_to='lodge/')),
                ('water', models.CharField(choices=[('NO', 'No'), ('BH', 'Borehole'), ('WL', 'Well')], max_length=2)),
                ('light', models.CharField(choices=[('GT', 'General Transformer'), ('PT', 'Private Transformer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SC', 'Self Contain'), ('SR', 'Single Room')], max_length=2)),
                ('number', models.IntegerField(blank=True)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('availabe', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agent')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.lodge')),
            ],
        ),
    ]
