# Generated by Django 4.2 on 2023-11-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='rooms/'),
        ),
    ]
