# Generated by Django 4.2 on 2023-11-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0004_room_image1_room_image2_room_image3_room_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image6',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
    ]
