# Generated by Django 4.2 on 2023-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0005_room_image6'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='lodge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
