# Generated by Django 4.2 on 2023-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0008_alter_lodge_options_lodge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique_for_date='created_at'),
            preserve_default=False,
        ),
    ]
