# Generated by Django 4.2 on 2023-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0010_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image6',
        ),
    ]
