# Generated by Django 4.2 on 2023-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0011_remove_room_image1_remove_room_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
