# Generated by Django 4.2 on 2023-12-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0013_alter_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lodges/')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodges.lodge')),
            ],
        ),
    ]
