# Generated by Django 4.2 on 2023-12-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0014_lodgeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
