# Generated by Django 4.2 on 2023-12-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0015_lodge_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LodgeAmmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammenity', models.CharField(max_length=255)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.lodge')),
            ],
        ),
    ]
