# Generated by Django 4.2 on 2023-12-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0016_lodge_description_lodgeammenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeammenities',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ammenities', to='lodges.lodge'),
        ),
    ]
