# Generated by Django 4.2 on 2023-12-28 10:29

import django.core.validators
from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0019_alter_lodge_price_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), lodges.validation.is_valid_video]),
        ),
    ]
