# Generated by Django 4.2 on 2023-12-28 13:54

import django.core.validators
from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0020_alter_lodge_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv']), lodges.validation.is_valid_video, lodges.validation.validate_video_size]),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv']), lodges.validation.is_valid_video, lodges.validation.validate_video_size]),
        ),
    ]
