# Generated by Django 4.2 on 2023-12-28 14:07

from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0021_room_video_alter_lodge_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='lodge/', validators=[lodges.validation.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='lodgeimage',
            name='image',
            field=models.ImageField(upload_to='lodges/', validators=[lodges.validation.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='rooms/', validators=[lodges.validation.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='rooms/', validators=[lodges.validation.validate_image_size]),
        ),
    ]
