# Generated by Django 4.2 on 2024-01-06 15:47

from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0024_alter_lodge_cover_image_alter_room_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='lodge/', validators=[lodges.validation.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='rooms/', validators=[lodges.validation.validate_image_size]),
        ),
    ]
