# Generated by Django 4.2 on 2024-01-06 15:51

import django.core.validators
from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0025_alter_lodge_cover_image_alter_room_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='cover_image',
            field=models.ImageField(default='11756.jpg', upload_to='lodge/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv']), lodges.validation.validate_image_size]),
        ),
    ]
