# Generated by Django 4.2 on 2024-01-06 15:56

import django.core.validators
from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0028_alter_lodge_cover_image_alter_lodgeimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv']), lodges.validation.is_valid_video]),
        ),
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv']), lodges.validation.is_valid_video]),
        ),
    ]
