# Generated by Django 4.2 on 2024-01-06 16:36

import cloudinary_storage.storage
from django.db import migrations, models
import lodges.validation


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0029_alter_lodge_video_alter_room_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[lodges.validation.is_valid_video]),
        ),
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[lodges.validation.is_valid_video]),
        ),
    ]
